package fptcloud_mgpu_cluster

var descriptions = map[string]string{
	"vpc_id":          "VPC ID",
	"cluster_name":    "Cluster name",
	"k8s_version":     "Kubernetes version",
	"purpose":         "Cluster purpose",
	"pod_network":     "Pod network (subnet ID)",
	"pod_prefix":      "Pod network (prefix)",
	"service_network": "Service network (subnet ID)",
	"service_prefix":  "Service prefix (prefix)",

	"k8s_max_pod":  "Max pods per node",
	"network_type": "Network type for the cluster (calico or cilium)",

	"name":                  "Pool name",
	"storage_profile":       "Pool storage profile",
	"hpc_flavor_id":         "HPC bare metal flavor ID for the pool",
	"hpc_flavor_name":       "HPC bare metal flavor name for the pool (optional)",
	"hpc_number_server":     "Number of bare metal servers in the pool",
	"gpu_template_version":  "GPU template version (optional)",
	"network_name":          "Subnet name",
	"network_id":            "Subnet ID",
	"network_overlay":       "Whether to encapsulate pod traffic between different subnets or same subnet",
	"edge_gateway_id":       "Edge gateway ID, in the format of urn:vcloud:gateway:<uuid>",
	"worker_disk_size":      "Worker disk size",
	"is_enable_auto_repair": "Whether to enable auto-repair",
	// New/optional fields
	"tags":                     "List of tag IDs for the worker pool (optional)",
	"kv":                       "Label for the pool (optional)",
	"vgpu_id":                  "Virtual GPU ID (optional)",
	"max_client":               "Maximum number of clients (optional)",
	"gpu_sharing_client":       "GPU sharing client (optional)",
	"driver_installation_type": "Driver installation type (optional)",
	"internal_subnet_lb":       "Subnet used for the internal load balancer: subnet ID on OSP, subnet CIDR on VMW (optional)",
	"edge_gateway_name":        "Edge gateway name (optional)",
	"allowCidr":                "Allowed CIDR blocks for cluster endpoint access (optional)",
	"is_enable_auto_upgrade":   "Whether to enable auto-upgrade (optional)",
	"auto_upgrade_expression":  "Auto-upgrade cron expressions (optional)",
	"auto_upgrade_timezone":    "Timezone for auto-upgrade (optional)",
	"cluster_autoscaler":       "Cluster autoscaler configuration block (optional)",
	"is_running":               "Whether the cluster is running (optional)",
	// Bare-metal-only top-level fields
	"default_storage_profile": "Default storage profile for the cluster (optional)",
	"network_node_prefix":     "Node network prefix length (optional)",
	"load_balancer_type":      "Load balancer type for the cluster (optional)",
	"secret_binding_name":     "Secret binding name (optional)",
	"ssh_id":                  "SSH key ID to install on the nodes (optional)",
	"ssh_name":                "SSH key name to install on the nodes (optional)",
	"ssh_public_key":          "SSH public key to install on the nodes (optional)",
	// software operators
	"software":             "Software installed on the cluster: which operator, at which version",
	"software_type":        "Software to install: gpu_operator, network_operator, slurm_operator, or vgpu_scheduler",
	"software_version":     "Version of the selected software",
	"cluster_mig_strategy": "MIG strategy (single or mixed); only for software_type gpu_operator",
	// cluster_autoscaler subfields
	"is_enable_auto_scaling":           "Enable cluster autoscaling (optional)",
	"scale_down_delay_after_add":       "Delay after adding a node before scale down (seconds, optional)",
	"scale_down_delay_after_delete":    "Delay after deleting a node before scale down (seconds, optional)",
	"scale_down_delay_after_failure":   "Delay after scale down failure (seconds, optional)",
	"scale_down_unneeded_time":         "Time a node should be unneeded before scale down (seconds, optional)",
	"scale_down_utilization_threshold": "Utilization threshold for scale down (optional)",
	"scan_interval":                    "Interval between autoscaler scans (seconds, must be 1-3600, optional)",
	"expander":                         "Autoscaler expander strategy (optional)",
	// cluster_endpoint_access subfields
	"cluster_endpoint_access_type":       "Type of cluster endpoint access (public, private, or mixed)",
	"cluster_endpoint_access_allow_cidr": "Allowed CIDR blocks for cluster endpoint access",
	// hibernation schedules
	"hibernation_schedules": "List of hibernation schedules for the cluster",
	"start":                 "Cron expression for when hibernation should start",
	"end":                   "Cron expression for when hibernation should end",
	"location":              "Timezone for the hibernation schedule (e.g., Asia/Bangkok)",
}
