package fptcloud_mfke

var descriptions = map[string]string{
	"vpc_id":          "VPC ID",
	"cluster_name":    "Cluster name",
	"k8s_version":     "Kubernetes version",
	"purpose":         "Cluster purpose",
	"pod_network":     "Pod network (subnet ID)",
	"pod_prefix":      "Pod network (prefix)",
	"service_network": "Service network (subnet ID)",
	"service_prefix":  "Service prefix (prefix)",

	"k8s_max_pod":         "Max pods per node",
	"network_node_prefix": "Network node prefix",

	"name":                  "Pool name",
	"storage_profile":       "Pool storage profile",
	"worker_type":           "Worker flavor ID",
	"network_name":          "Subnet name",
	"network_id":            "Subnet ID",
	"network_overlay":       "Whether to encapsulate pod traffic between different subnets or same subnet",
	"edge_gateway_id":       "Edge gateway ID, in the format of urn:vcloud:gateway:<uuid>",
	"worker_disk_size":      "Worker disk size",
	"scale_min":             "Minimum number of nodes for autoscaling",
	"scale_max":             "Maximum number of nodes for autoscaling",
	"auto_scale":            "Whether to enable autoscaling",
	"is_enable_auto_repair": "Whether to enable auto-repair",
	// New/optional fields
	"tags":                    "Tags for the pool (optional)",
	"kv":                      "Key-value pairs for the pool (optional)",
	"vGpuId":                  "Virtual GPU ID (optional)",
	"maxClient":               "Maximum number of clients (optional)",
	"gpuSharingClient":        "GPU sharing client (optional)",
	"driverInstallationType":  "Driver installation type (optional)",
	"internal_subnet_lb":      "Internal subnet for load balancer (optional)",
	"edge_gateway_name":       "Edge gateway name (optional)",
	"allowCidr":               "Allowed CIDR blocks for cluster endpoint access (optional)",
	"is_enable_auto_upgrade":  "Whether to enable auto-upgrade (optional)",
	"auto_upgrade_expression": "Auto-upgrade cron expressions (optional)",
	"auto_upgrade_timezone":   "Timezone for auto-upgrade (optional)",
	"cluster_autoscaler":      "Cluster autoscaler configuration block (optional)",
	// cluster_autoscaler subfields
	"isEnableAutoScaling":           "Enable cluster autoscaling (optional)",
	"scaleDownDelayAfterAdd":        "Delay after adding a node before scale down (seconds, optional)",
	"scaleDownDelayAfterDelete":     "Delay after deleting a node before scale down (seconds, optional)",
	"scaleDownDelayAfterFailure":    "Delay after scale down failure (seconds, optional)",
	"scaleDownUnneededTime":         "Time a node should be unneeded before scale down (seconds, optional)",
	"scaleDownUtilizationThreshold": "Utilization threshold for scale down (optional)",
	"scanInterval":                  "Interval between autoscaler scans (seconds, optional)",
	"expander":                      "Autoscaler expander strategy (optional)",
}
